### get all post
GET /api/posts
Host: blog.test

### get one post
GET /api/post/11
Host: blog.test

### create a new post
POST /api/post
Host: blog.test
Content-Type: application/json

{
    "writer_id": "1",
    "title": "programming",
    "body": "this post about programmersg",
    "image_path": "storage/images/tbVvSlA6LXuOUzYBRsuZ6dW8T0qdBdOmANkuY9tL.jpg"
}


### update a post
PUT  /api/post/2
Host: blog.test
Content-Type: application/json

{
    "writer_id": "1",
    "title": "war",
    "body": "this post about war",
    "image_path": "storage/images/tbVvSlA6LXuOUzYBRsuZ6dW8T0qdBdOmANkuY9tL.jpg"
}


### destroy post
POST /api/post/1
Host: blog.test
Content-Type: application/json



### search with title post
GET /api/post/search/pro
Host: blog.test
Content-Type: application/json

