### get all writer
GET /api/writers
Host: blog.test

### get one writer 
GET /api/writer/2
Host: blog.test
Content-Type: application/json


### create new wirter
POST /api/writer
Host: blog.test
Content-Type: application/json

{
    "name": "mosi",
    "phone": "09876789",
    "email": "mosi@gmail.com",
    "avatar": "public/images/7o7uUg1ZKui7amXdLVrtRC6HwcVG8z34wyTAoZ6I.jpg "
}


### update
PUT  /api/writer/1
Host: blog.test
Content-Type: application/json

{
    "name": "mostafa",
    "email": "mostafa@gmail.com",
    "phone": "0901127131",
    "avatar": "images/QFI1hqsbCN3WGPGKPSxAqswcm3ep53bBbmZiQR4y.jpg"
}


### delete writer 
POST /api/writer/4
Host: blog.test
Content-Type: application/json



### search by name
GET /api/writer/search/mosi
Host: blog.test
Content-Type: application/json
