### get all writer
GET /api/writers
Host: blog.test

### get one writer 
GET /api/writers/1
Host: blog.test
Content-Type: application/json


### create a new wirter
POST /api/writers
Host: blog.test
Content-Type: application/json

{
    "name": "amsir2",
    "phone": "09871617891",
    "email": "amis1r@gmail.com",
    "avatar": "storage/images/lA9dV9URHG4hQBgldVI2lPunvcZVTGx3ubTx43Oi.jpg"
}

### update
PUT  /api/writers/2
Host: blog.test
Content-Type: application/json

{
    "name": "mostafaa",
    "email": "mostafaa@gmail.com",
    "phone": "09011271231",
    "avatar": "storage/images/tbVvSlA6LXuOUzYsBRsuZ6dW8T0qdBdOmANkuY9tL.jpg"
}


### delete writer 
POST /api/writers/1
Host: blog.test
Content-Type: application/json



### search by name
GET /api/writers/search/mos
Host: blog.test
Content-Type: application/json
