### get all comment
GET /api/comments
Host: blog.test

### get one comment 
GET /api/comments/15
Host: blog.test
Content-Type: application/json


### create a new comment
POST /api/comments
Host: blog.test
Content-Type: application/json

{
    "comment": "the post was sucks",
    "name": "mosi",
    "email": "mosi@gmail.com",
    "type": "posdt",
    "commentable_id": "1"
}

### update
PUT  /api/comments/8
Host: blog.test
Content-Type: application/json

{
    "comment": "test update method",
    "name": "mostafaas",
    "email": "mostafqaa@gmail.com"
}


### delete comment 
POST /api/comments/2
Host: blog.test
Content-Type: application/json
